FROM nginx:alpine 
# Устанавливаем curl
RUN apk --no-cache add curl 
COPY . /usr/share/nginx/html
EXPOSE 80
HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl -f http://localhost/ || exit 1
