FROM python:3.11-slim

WORKDIR /app
COPY . /app


RUN pip install --no-cache-dir fastapi uvicorn psycopg2-binary requests

EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl -f http://localhost:8000/docs || exit 1

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
